# Generated by Django 4.0.3 on 2022-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Fa', 'Fashion'), ('El', 'Electronics'), ('M&A', 'Mobiles & Accesories'), ('C&A', 'Computers & Accesories'), ('Bo', 'Books'), ('Dec', 'Decors')], max_length=180)),
                ('price', models.FloatField()),
            ],
        ),
    ]
