# Generated by Django 3.2.4 on 2021-09-17 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 8, 46, 49, 775920, tzinfo=utc)),
        ),
    ]
