# Generated by Django 3.2.4 on 2021-09-17 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 9, 22, 10, 417000, tzinfo=utc)),
        ),
    ]
