# Generated by Django 3.2.4 on 2021-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_prodimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='Not Available', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodImg',
            field=models.ImageField(upload_to='products/imgs/'),
        ),
    ]
